import type { Metadata } from "next";
import { Montserrat, Space_Grotesk } from "next/font/google";
import localFont from "next/font/local";

import { cn } from "@/lib/utils";

import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const clashGrotesk = localFont({
  src: "../fonts/ClashGrotesk-Variable.woff2",
  variable: "--font-clash-grotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        montserrat.variable,
        spaceGrotesk.variable,
        clashGrotesk.variable,
        "bg-black text-white",
      )}
    >
      <body>{children}</body>
    </html>
  );
}
